name: Deploy
inputs:
  system-env:
    required: true
  output-path:
    required: true
  aws-deploy-role-arn:
    required: true
  frontend-bucket-name:
    required: true
  frontend-distribution-id:
    required: true
  service-name:
    required: true
  slack-channel-id:
    required: true
  slack-bot-token:
    required: true
  github-token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Load Dist
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.output-path }}
        path: ${{ inputs.output-path }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: "${{ inputs.aws-deploy-role-arn }}"
        aws-region: ap-northeast-1
        role-duration-seconds: 900
        role-session-name: GitHubActionsSession
    - name: S3 Sync
      run: aws s3 sync ./${{ inputs.output-path }} s3://${{ inputs.frontend-bucket-name }} --delete
      shell: bash
    - name: Cloudfront Create Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ inputs.frontend-distribution-id }} --paths '/*'
      shell: bash
