name: Cache Node Modules
description: Cache Node Modules
inputs:
  working-directory:
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache-yarn
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/yarn.lock', inputs.working-directory)) }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/yarn.lock', inputs.working-directory)) }}