name: Build
inputs:
  output-path:
    required: true
  working-directory:
    required: true
  next-public-google-id:
    required: true
  next-public-microcms-service-id:
    required: true
  next-public-microcms-api-key:
    required: true
  mtt-domain:
    required: true
  next-public-api-endpoint:
    required: true
  next-public-api-name:
    required: true
  next-public-region:
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Node Modules
      uses: ./.github/actions/cache-node-modules
      with:
        working-directory: ${{ inputs.working-directory }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Yarn Build
      run: yarn build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        MTT_DOMAIN: ${{ inputs.mtt-domain }}
        OUTPUT_PATH: ${{ inputs.output-path }}
        NEXT_PUBLIC_GOOGLE_ID: ${{ inputs.next-public-google-id }}
        NEXT_PUBLIC_MICROCMS_SERVICE_ID: ${{ inputs.next-public-microcms-service-id }}
        NEXT_PUBLIC_MICROCMS_API_KEY: ${{ inputs.next-public-microcms-api-key }}
        NEXT_PUBLIC_REGION: ${{ inputs.next-public-region }}
        NEXT_PUBLIC_API_NAME: ${{ inputs.next-public-api-name }}
        NEXT_PUBLIC_API_ENDPOINT: ${{ inputs.next-public-api-endpoint }}
    - name: Save Dist
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.output-path }}"
        path: ${{ inputs.working-directory }}/${{ inputs.output-path }}
